apiVersion: v1
kind: Service
metadata:
  name: helloworldserver1webui
spec:
  ports:
  - name: webui
    nodePort: 30839
    port: 30839
    targetPort: 8062
  selector:
    app: helloworldserver1
  type: NodePort
