apiVersion: v1
kind: Service
metadata:
  name: helloworldclient1
spec:
  ports:
  - name: protobuf-api
    nodePort: 32019
    port: 32019
    targetPort: 8061
  selector:
    app: helloworldclient1
  type: NodePort
