apiVersion: v1
kind: Service
metadata:
  name: helloworldclient2
spec:
  ports:
  - name: protobuf-api
    nodePort: 30102
    port: 30102
    targetPort: 8061
  selector:
    app: helloworldclient2
  type: NodePort
