apiVersion: v1
kind: Service
metadata:
  name: helloworldclient2webui
spec:
  ports:
  - name: webui
    nodePort: 31798
    port: 31798
    targetPort: 8062
  selector:
    app: helloworldclient2
  type: NodePort
