apiVersion: v1
kind: Service
metadata:
  name: helloworldclient1webui
spec:
  ports:
  - name: webui
    nodePort: 30247
    port: 30247
    targetPort: 8062
  selector:
    app: helloworldclient1
  type: NodePort
