---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node21
  labels:
    app: node21
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node21
  template:
    metadata:
      labels:
        app: node21
    spec:
      containers:
      - name: node21
        image: vaibhavtechie/node2-image:latest
        ports:
        - name: protobuf-api
          containerPort: 8061
        - name: webui
          containerPort: 8062
