apiVersion: v1
kind: Service
metadata:
  name: orchestratorwebui
spec:
  ports:
  - name: webui
    nodePort: 32013
    port: 32013
    targetPort: 8062
  selector:
    app: orchestrator
  type: NodePort
